export enum EntityName {
	Otp = "otp",
	User = "user",
	Post = "post",
	Media = "media",
	Album = "album",
	Story = "story",
	Block = "block",
	Follow = "follow",
	Profile = "profile",
	Hashtag = "hashtag",
	PostLike = "post_like",
	PostComment = "post_comment",
	PostBookmark = "post_bookmarks",
	FollowRequest = "follow_request",
	PostCommentLike = "post_comment_like",
}
